gxt -g VCS -i "ENGLISH.txt" -o "../../gamefiles/TEXT/ENGLISH.gxt"
gxt -g VCS -i "french.txt" -o "../../gamefiles/TEXT/french.gxt"
gxt -g VCS -i "german.txt" -o "../../gamefiles/TEXT/german.gxt"
gxt -g VCS -i "italian.txt" -o "../../gamefiles/TEXT/italian.gxt"
gxt -g VCS -i "spanish.txt" -o "../../gamefiles/TEXT/spanish.gxt"